
INSERT INTO USER VALUES ('muyQnexv84759462', '3r@uJAZvfDZ8v0', 'Russell', 'forsakenMare3', 'Russell@nate.com' )
INSERT INTO USER VALUES ('JeeEKUku72725499', 'aadN2PFy', 'Richard', 'alertPup3', 'Richard@outlook.com' )
INSERT INTO USER VALUES ('ZYNnGLCd54153969', 'FySt2jHiAxWyl7D', 'Donna', 'unhappyBuzzard5', 'Donna@outlook.com' )
INSERT INTO USER VALUES ('jOreXCIb28414933', 'oBSFQLqWGtyfyY!uNt', 'James', 'mellowRaisins6', 'James@outlook.com' )
INSERT INTO USER VALUES ('FKXtXhit85681812', '04cUvr09A0NU8U', 'Rhonda', 'mercifulBasmati3', 'Rhonda@daum.com' )
INSERT INTO USER VALUES ('EBukqOHS77133484', 'Cxv2G2vHdxNWJxBxCY8N', 'Dorothy', 'finickyBass6', 'Dorothy@gmail.com' )
INSERT INTO USER VALUES ('hzoONQBz12765315', 'ewd05SRt4r', 'Leah', 'gloomyPudding7', 'Leah@korea.com' )
INSERT INTO USER VALUES ('JcgujaVd58221616', 'zRrcy8TNlKn4OO', 'Walter', 'empathicBaboon8', 'Walter@naver.com' )
INSERT INTO USER VALUES ('MGJNBtcD64779129', '8IKNZx1kuiToTogswVn1', 'Rosemary', 'curiousPup6', 'Rosemary@gmail.com' )
INSERT INTO USER VALUES ('BrLSpBXg16534135', 'QyvDfgeGXAuxK', 'Angelo', 'giddyBuck6', 'Angelo@korea.com' )
INSERT INTO USER VALUES ('cqfALRgp37915336', 'MQS4h7yh', 'Kenneth', 'worriedTermite5', 'Kenneth@gmail.com' )
INSERT INTO USER VALUES ('QQCqjuup33412851', '5@n5YN8CZIw5pEudTP', 'Mammie', 'madSheep7', 'Mammie@nate.com' )
INSERT INTO USER VALUES ('YUSYjStU68441869', 'K4sDPb@2qdk', 'Judy', 'soreMackerel7', 'Judy@naver.com' )
INSERT INTO USER VALUES ('uJxvRLDN78296232', 'rylsT9GKMtxeTMeLU3', 'Frieda', 'peacefulIcecream7', 'Frieda@naver.com' )
INSERT INTO USER VALUES ('DJBSNcvv85366612', '8t@7FThGI7pSZxx', 'Steve', 'debonairEagle9', 'Steve@nate.com' )
INSERT INTO USER VALUES ('wzvnwDDS81293377', 'Swgqr2fio', 'Alisha', 'shamefulBass5', 'Alisha@naver.com' )
INSERT INTO USER VALUES ('PKlRzFMv58342325', 'L6QFiLA@JpK', 'Willard', 'adoringRat1', 'Willard@korea.com' )
INSERT INTO USER VALUES ('XtWUkJDM58415927', 'tUr7johybqrx@LX!A', 'Kesha', 'contentPorpoise2', 'Kesha@korea.com' )
INSERT INTO USER VALUES ('BjdUFLdk16854869', 'vdsfRqztjTEpl6!f0', 'Melody', 'grizzledOryx4', 'Melody@outlook.com' )
INSERT INTO USER VALUES ('iHXNFzYE16794666', 'x1twpxzoMU', 'Dennis', 'lovesickCamel7', 'Dennis@outlook.com' )
INSERT INTO USER VALUES ('NKfocFks78841575', 'vsEPiVW9tuFe', 'Deborah', 'scornfulBasmati1', 'Deborah@outlook.com' )
INSERT INTO USER VALUES ('LlafUiRp65235537', 'OsTOYWbNv5Bi13akV6', 'Hulda', 'holisticDoves5', 'Hulda@daum.com' )
INSERT INTO USER VALUES ('jpZEuDjV26521625', 'WL7qIWGyGj', 'Sherika', 'decimalPolenta4', 'Sherika@outlook.com' )
INSERT INTO USER VALUES ('pEmdTrTh95199952', 'ThSAGZ9b0zk', 'Victoria', 'anxiousOil0', 'Victoria@daum.com' )
INSERT INTO USER VALUES ('fqwlIzpC52969632', 'rgYUHSr8T!M5toldyw', 'Rosie', 'somberCordial2', 'Rosie@korea.com' )
INSERT INTO USER VALUES ('SIZgOpts96969361', 'FL5biX6anHOmzBmF4Ne', 'Henry', 'abjectJerky2', 'Henry@yahoo.com' )
INSERT INTO USER VALUES ('nOJhULvR98257951', 'yiE9E0YAaadVG8', 'Robert', 'goofyCrane1', 'Robert@yahoo.com' )
INSERT INTO USER VALUES ('ceyFkLVy25633386', 'hyR8pFN4bxM7p5qK', 'Roger', 'needyTermite9', 'Roger@korea.com' )
INSERT INTO USER VALUES ('WEjzQwnb76169673', 'N!LIGqSbo6v', 'Anthony', 'gleefulWigeon2', 'Anthony@nate.com' )
INSERT INTO USER VALUES ('eigPRmZF34319146', 'bifqEt3EuYNEsECKl', 'Kenneth', 'gleefulOatmeal0', 'Kenneth@gmail.com' )
INSERT INTO USER VALUES ('dIwxMzyq38947999', 'y7htwZylDatG', 'Lisa', 'amusedLion1', 'Lisa@outlook.com' )
INSERT INTO USER VALUES ('SyIuriDG91522871', '4aN80ur5rsMUPQDDz', 'Aaron', 'lazyWasp7', 'Aaron@naver.com' )
INSERT INTO USER VALUES ('hjVygJIy98433954', 'lJe2HpUTrHeCeAeWKwL', 'Robert', 'anxiousOcelot0', 'Robert@daum.com' )
INSERT INTO USER VALUES ('XRBSykko75639327', 'P17omYmMc!SYT2f', 'Mary', 'madPretzels7', 'Mary@daum.com' )
INSERT INTO USER VALUES ('SSOLLSQA67646696', '9r1rQ23HxBLR', 'Ramon', 'brainyLapwing5', 'Ramon@daum.com' )
INSERT INTO USER VALUES ('uEokMapq45344339', '19GZwkldbXH7TLecBok', 'Sheila', 'jumpySausage4', 'Sheila@korea.com' )
INSERT INTO USER VALUES ('njgOaGti95555589', 'MVbZ3pHXGwWF6K59!a', 'Charles', 'crummyCoati2', 'Charles@nate.com' )
INSERT INTO USER VALUES ('VZWgkacs27989566', 'pYl2sbMQajV', 'Brandy', 'eagerApricots0', 'Brandy@daum.com' )
INSERT INTO USER VALUES ('qZwAAhvL67464982', '2cIuNUom1ci@', 'Tara', 'solidHyena6', 'Tara@gmail.com' )
INSERT INTO USER VALUES ('qBcZbBVR41314487', 'qvQcc1C89RkHmGR71', 'Joshua', 'dreadfulFish2', 'Joshua@korea.com' )
INSERT INTO USER VALUES ('flFBXcwv91684292', 'NeGracG04KPzo3MIcO', 'Jason', 'insecureHyena8', 'Jason@korea.com' )
INSERT INTO USER VALUES ('dEcCldCf96376616', 'xWobXIFz6OLconWQfT', 'Carrie', 'murkyShads5', 'Carrie@yahoo.com' )
INSERT INTO USER VALUES ('rwzhUxIx18233413', 'y9F1imSNe3iDL', 'Simon', 'worldlyCrane4', 'Simon@daum.com' )
INSERT INTO USER VALUES ('QXcUEYlB79719573', '4yU3jpvybTchQ', 'Randy', 'finickyToucan1', 'Randy@yahoo.com' )
INSERT INTO USER VALUES ('VBrtetYD49833178', 'yWxfFRrBsoaYVPyy', 'Christina', 'peacefulTomatoe9', 'Christina@korea.com' )
INSERT INTO USER VALUES ('LBmIQCLM87316588', 'SRMXEdA2KGyalHp', 'Douglas', 'dearGarlic8', 'Douglas@daum.com' )
INSERT INTO USER VALUES ('wRJRfUdN26178521', 'mNyKjrcp8kfo', 'David', 'boredPear1', 'David@korea.com' )
INSERT INTO USER VALUES ('bSWvEWDI55155924', '47Kaa6qx4TFYRCJNV', 'Salvador', 'gleefulDoves8', 'Salvador@nate.com' )
INSERT INTO USER VALUES ('vesAlwpx15335755', '!zBZRUW2UAzpmcnq', 'Larry', 'gleefulBuck3', 'Larry@gmail.com' )
INSERT INTO USER VALUES ('QvfJBQhn18254326', 'h@VWk4a4kAu', 'Judith', 'amusedLeopard9', 'Judith@nate.com' )

COMMIT;

INSERT INTO YOUTUBER VALUES (1, 'Louis' )
INSERT INTO YOUTUBER VALUES (2, 'Tyrone' )
INSERT INTO YOUTUBER VALUES (3, 'David' )
INSERT INTO YOUTUBER VALUES (4, 'Elvis' )
INSERT INTO YOUTUBER VALUES (5, 'Maisie' )
INSERT INTO YOUTUBER VALUES (6, 'Jonathan' )
INSERT INTO YOUTUBER VALUES (7, 'Lorraine' )
INSERT INTO YOUTUBER VALUES (8, 'Kim' )
INSERT INTO YOUTUBER VALUES (9, 'Felix' )
INSERT INTO YOUTUBER VALUES (10, 'John' )
INSERT INTO YOUTUBER VALUES (11, 'Ben' )
INSERT INTO YOUTUBER VALUES (12, 'Sharon' )
INSERT INTO YOUTUBER VALUES (13, 'Richard' )
INSERT INTO YOUTUBER VALUES (14, 'Shirley' )
INSERT INTO YOUTUBER VALUES (15, 'Linda' )
INSERT INTO YOUTUBER VALUES (16, 'Norris' )
INSERT INTO YOUTUBER VALUES (17, 'Amie' )
INSERT INTO YOUTUBER VALUES (18, 'Michael' )
INSERT INTO YOUTUBER VALUES (19, 'Jeremy' )
INSERT INTO YOUTUBER VALUES (20, 'Dorothy' )
INSERT INTO YOUTUBER VALUES (21, 'Christy' )
INSERT INTO YOUTUBER VALUES (22, 'Rebecca' )
INSERT INTO YOUTUBER VALUES (23, 'Frank' )
INSERT INTO YOUTUBER VALUES (24, 'Delbert' )
INSERT INTO YOUTUBER VALUES (25, 'Kelly' )
INSERT INTO YOUTUBER VALUES (26, 'Kathleen' )
INSERT INTO YOUTUBER VALUES (27, 'Jack' )
INSERT INTO YOUTUBER VALUES (28, 'Linda' )
INSERT INTO YOUTUBER VALUES (29, 'John' )
INSERT INTO YOUTUBER VALUES (30, 'Allison' )
INSERT INTO YOUTUBER VALUES (31, 'Brandy' )
INSERT INTO YOUTUBER VALUES (32, 'George' )
INSERT INTO YOUTUBER VALUES (33, 'Amy' )
INSERT INTO YOUTUBER VALUES (34, 'Anna' )
INSERT INTO YOUTUBER VALUES (35, 'Annie' )
INSERT INTO YOUTUBER VALUES (36, 'Albert' )
INSERT INTO YOUTUBER VALUES (37, 'Calvin' )
INSERT INTO YOUTUBER VALUES (38, 'Janie' )
INSERT INTO YOUTUBER VALUES (39, 'Nancy' )
INSERT INTO YOUTUBER VALUES (40, 'Larry' )
INSERT INTO YOUTUBER VALUES (41, 'Joann' )
INSERT INTO YOUTUBER VALUES (42, 'Norman' )
INSERT INTO YOUTUBER VALUES (43, 'Bernice' )
INSERT INTO YOUTUBER VALUES (44, 'Arthur' )
INSERT INTO YOUTUBER VALUES (45, 'Arthur' )
INSERT INTO YOUTUBER VALUES (46, 'Catherine' )
INSERT INTO YOUTUBER VALUES (47, 'Roxanne' )
INSERT INTO YOUTUBER VALUES (48, 'John' )
INSERT INTO YOUTUBER VALUES (49, 'Karin' )
INSERT INTO YOUTUBER VALUES (50, 'Dara' )

COMMIT;

INSERT INTO PERFORMER VALUES (1, 'Eva', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (2, 'Ryan', 'Comedian' )
INSERT INTO PERFORMER VALUES (3, 'Troy', 'Streamer' )
INSERT INTO PERFORMER VALUES (4, 'Harrison', 'Singer' )
INSERT INTO PERFORMER VALUES (5, 'Stephanie', 'Streamer' )
INSERT INTO PERFORMER VALUES (6, 'Maria', 'Critics' )
INSERT INTO PERFORMER VALUES (7, 'William', 'Athlete' )
INSERT INTO PERFORMER VALUES (8, 'Yetta', 'Singer' )
INSERT INTO PERFORMER VALUES (9, 'Minerva', 'Athlete' )
INSERT INTO PERFORMER VALUES (10, 'Tyrone', 'Animal' )
INSERT INTO PERFORMER VALUES (11, 'Charles', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (12, 'Kimberly', 'Animal' )
INSERT INTO PERFORMER VALUES (13, 'Sharon', 'ProGamer' )
INSERT INTO PERFORMER VALUES (14, 'Shannon', 'ProGamer' )
INSERT INTO PERFORMER VALUES (15, 'Inez', 'Actor' )
INSERT INTO PERFORMER VALUES (16, 'Brent', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (17, 'Ronnie', 'ProGamer' )
INSERT INTO PERFORMER VALUES (18, 'Lisa', 'Actor' )
INSERT INTO PERFORMER VALUES (19, 'Vernie', 'Animal' )
INSERT INTO PERFORMER VALUES (20, 'Carl', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (21, 'Fidela', 'Animation character' )
INSERT INTO PERFORMER VALUES (22, 'Margaret', 'Athlete' )
INSERT INTO PERFORMER VALUES (23, 'Kevin', 'Guest' )
INSERT INTO PERFORMER VALUES (24, 'Cecil', 'Animal' )
INSERT INTO PERFORMER VALUES (25, 'Gayle', 'ProGamer' )
INSERT INTO PERFORMER VALUES (26, 'Minnie', 'Singer' )
INSERT INTO PERFORMER VALUES (27, 'Joyce', 'Singer' )
INSERT INTO PERFORMER VALUES (28, 'Patrick', 'ProGamer' )
INSERT INTO PERFORMER VALUES (29, 'Randall', 'Comedian' )
INSERT INTO PERFORMER VALUES (30, 'Kelli', 'Animation character' )
INSERT INTO PERFORMER VALUES (31, 'Bette', 'Streamer' )
INSERT INTO PERFORMER VALUES (32, 'Anna', 'Animal' )
INSERT INTO PERFORMER VALUES (33, 'Maria', 'Guest' )
INSERT INTO PERFORMER VALUES (34, 'May', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (35, 'Erin', 'ProGamer' )
INSERT INTO PERFORMER VALUES (36, 'Robby', 'Animation character' )
INSERT INTO PERFORMER VALUES (37, 'Doris', 'ProGamer' )
INSERT INTO PERFORMER VALUES (38, 'Dale', 'Actor' )
INSERT INTO PERFORMER VALUES (39, 'Lydia', 'Comedian' )
INSERT INTO PERFORMER VALUES (40, 'George', 'ProGamer' )
INSERT INTO PERFORMER VALUES (41, 'Santiago', 'Streamer' )
INSERT INTO PERFORMER VALUES (42, 'Brenda', 'Actor' )
INSERT INTO PERFORMER VALUES (43, 'Curtis', 'Comedian' )
INSERT INTO PERFORMER VALUES (44, 'Brenda', 'Comedian' )
INSERT INTO PERFORMER VALUES (45, 'Justin', 'Virtual Human' )
INSERT INTO PERFORMER VALUES (46, 'Renee', 'Singer' )
INSERT INTO PERFORMER VALUES (47, 'Matthew', 'Athlete' )
INSERT INTO PERFORMER VALUES (48, 'Elizabeth', 'ProGamer' )
INSERT INTO PERFORMER VALUES (49, 'Mary', 'Athlete' )
INSERT INTO PERFORMER VALUES (50, 'Thomas', 'Virtual Human' )

COMMIT;

INSERT INTO GENRE VALUES (1, 'Animation' )
INSERT INTO GENRE VALUES (2, 'Beuty' )
INSERT INTO GENRE VALUES (3, 'Makeup' )
INSERT INTO GENRE VALUES (4, 'Comedy' )
INSERT INTO GENRE VALUES (5, 'Critics' )
INSERT INTO GENRE VALUES (6, 'Review' )
INSERT INTO GENRE VALUES (7, 'DIY' )
INSERT INTO GENRE VALUES (8, 'Education' )
INSERT INTO GENRE VALUES (9, 'Fashion' )
INSERT INTO GENRE VALUES (10, 'Muckbang' )
INSERT INTO GENRE VALUES (11, 'Cooking' )
INSERT INTO GENRE VALUES (12, 'Gaming' )
INSERT INTO GENRE VALUES (13, 'Health' )
INSERT INTO GENRE VALUES (14, 'Fitness' )
INSERT INTO GENRE VALUES (15, 'Music' )
INSERT INTO GENRE VALUES (16, 'News' )
INSERT INTO GENRE VALUES (17, 'Podcaster' )
INSERT INTO GENRE VALUES (18, 'Sports' )
INSERT INTO GENRE VALUES (19, 'Technology' )
INSERT INTO GENRE VALUES (20, 'Vlogger' )
INSERT INTO GENRE VALUES (21, 'Science' )
INSERT INTO GENRE VALUES (22, 'Lifestyle' )

COMMIT;

